### ISSUE TITLE
Uso de DecimalFormat

### ISSUE THREAD

**Issue by ijaureguialzo** [dave-egibide/ud2-elementos-programa#6]
Reescribe los ejercicios sin usar el DecimalFormat y eligiendo bien el tipo de dato. Si necesitas un entero usa `int` y si necesitas decimales `double`, pero no trabajes siempre con `double` y conviertas a entero, te acabará dando problemas.

**Comment by dave-egibide** [comment]
Solucionado en versión simplificada.
