### ISSUE TITLE
Ejercicio 10, 11, 17, ...

### ISSUE THREAD

**Issue by ijaureguialzo** [dave-egibide/ud2-elementos-programa#8]
### Observaciones

En vez de esto:
```java
if ((new String("F").equals(x))) {
```
Escribe:
```java
if (x.equals("F")) {
```
Queda más claro y funciona igual.

### Mejoras necesarias

Revisa esas comparaciones, no es el mejor modo de escribirlas.

**Comment by dave-egibide** [comment]
Todas reescritas.
